In [2]:
import numpy as np 
import pandas as pd
import scipy.special

In [3]:
def digamma(X):
    """
    takes in a argument X and returns d/dx(ln(gamma(X)))
    
    ----------------------------------------------------
    
    X : a numpy ndarray 
    
    """
    return scipy.special.digamma(X)

In [36]:
A = np.array([[1, 2, 3],[4, 5, 0]])

x = (A>0)

In [38]:
K = np.zeros(A.shape)

In [39]:
K

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
X = np.array([1, 2, 3])

In [46]:
X[x]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [20]:
def di_pochhammer(X, N):
    
    """
    takes in two arguments X, N and returns diagamma(X+N) - diagamma(X)
    
    -------------------------------------------------------------------
    
    X : a numpy ndarray 
    N : a numpy ndarray 
    
    """
    
    y = np.zeros(N.shape)
    
    a = (N > 0)
    
    if len(X) == 1 :
        y[a] = digamma(X+N[a]) - digamma(X)
        
    else : 
        y[a] = digamma(X[a]+N[a]) - digamma(X[a])
        
    return y 

In [21]:
def dirichlet_moment_match(p):
    
    a = np.mean(p)
    
    m2 = np.mean(p*p)
    
    ok = (a>0)
    
    s = (a[ok] - m2[ok]) / (m2[ok] - (a[ok]**2))
    
    s = np.median(s)
    
    a = a * s
    
    return a   

In [22]:
def polya_moment_match(data):
    
    s_data = np.sum(data, axis = 1).reshape((data.shape[0],1))
    
    p = data / np.tile(s_data+np.finfo(float).eps,(1, data.shape[1]))
    
    a = dirichlet_moment_match(p)
    
    return a

In [23]:
def pochhammer(X,N): 
    
    return scipy.special.poch(X, N)

In [24]:
A = np.array([[0, 1, 2],[2, 1, 0]])

np.sum(A, axis=0)

array([2, 2, 2])

In [25]:
def polya_logProb(a, data): 
    
    row_condition = (a.shape[0] == 1)
    
    s = np.full(np.sum(a))
    if row_condition :
        s_data = np.sum(a, axis=1)
        
        p = np.zeros((data.shape[0], 1))
        
        for k in range(0, data.shape[1]):
            dk = data[:, k]
            p += pochhammer(a[k], dk)
            
        p -= pochhammer(s, sdata)
        
        return p 
    
    else: 
        
        s_data = np.sum(data, axis=0)
        
        for i in range(0,data.shape[1]):
            p[i] = np.sum(scipy.special.gammaln(data[:,i] + a)) - scipy.special.gammaln(sdata[i] + s)
            
        p += scipy.special.gammaln(s) - np.sum(scipy.special.gammaln(a))
        
        return p

In [26]:
def polya_fit_simple(data):
    
    a = polya_moment_match(data)
    sdata = np.sum(data, axis=1)
    
    N, K = data.shape
    
    for iteration in range(0,1000):
        old_a = a
        sum_a = np.sum(a)
        
        if 0 :
            g = np.sum(digamma(data + np.tile(a, (N, 1)), axis=0)) - (N @ digamma(a))
            h = np.sum(digamma(sdata + sa)) - (N @ digamma(sa))
        
        else:
            g = np.sum(di_pochhammer(np.tile(a, (N, 1)), data),axis = 0)
            h = np.sum(di_pochhammer(sa, sdata)) 
        
        a = (a*g)/h
        
        if max(abs(a - old_a)) < 1e-6:
            break
    return a               

In [27]:
pwd

'/Users/adityagarg/Desktop/APL405.nosync/HW3_GARG_ADITYA_2019ME10770/HW3_GARG_ADITYA_Q2_2019ME10770'

In [28]:
import pymatreader as reader

data = reader.read_mat('Problem2.mat')

In [29]:
data

{'__header__': b'MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Sun Jan 20 18:58:21 2019',
 '__version__': '1.0',
 '__globals__': [],
 'data': {'y': array([ 0,  0,  2,  0,  1,  1,  0,  2,  1,  3,  0,  1,  1,  1, 54,  0,  0,
          1,  3,  0], dtype=uint8),
  'n': array([ 1083,   855,  3461,   657,  1208,  1025,   527,  1668,   583,
           582,   917,   857,   680,   917, 53637,   874,   395,   581,
           588,   383], dtype=uint16)}}

In [30]:
y = data['data']['y']
n = data['data']['n']

In [31]:
y = y.reshape((20,1))

In [32]:
n = n.reshape((20,1))

In [33]:
X = np.concatenate([y, n-y], axis=1)

In [34]:
X

array([[    0,  1083],
       [    0,   855],
       [    2,  3459],
       [    0,   657],
       [    1,  1207],
       [    1,  1024],
       [    0,   527],
       [    2,  1666],
       [    1,   582],
       [    3,   579],
       [    0,   917],
       [    1,   856],
       [    1,   679],
       [    1,   916],
       [   54, 53583],
       [    0,   874],
       [    0,   395],
       [    1,   580],
       [    3,   585],
       [    0,   383]], dtype=uint16)

In [47]:
alphas = polya_fit_simple(X)

AxisError: axis 1 is out of bounds for array of dimension 1